# Generated by Django 6.0 on 2026-01-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.PositiveIntegerField(default=465)),
                ('email_use_ssl', models.BooleanField(default=True)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='GreenWeb', max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=50)),
                ('api_url', models.URLField(default='http://sms.greenheritageit.com/smsapi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SSLCommerzConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('store_password', models.CharField(max_length=255)),
                ('sandbox', models.BooleanField(default=True)),
                ('success_url', models.URLField()),
                ('fail_url', models.URLField()),
                ('cancel_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
